server:
  # consul服务端口
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: virtual-01.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://192.168.1.3:${server.port}/actuator/health
