server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

  # zipkin/sleuth链路跟踪
  zipkin:
    base-url: http://virtual-01.com:9411
  sleuth:
    sampler:
      # 采样值介于0到1之间,1表示全部采集
      probability: 1

eureka:
  client:
    # 是否注册
    fetch-registry: true
    # 是否从Eureka 注册中心中获取自己的服务
    register-with-eureka: true
    service-url:
      # 集群版Eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版Eureka
      # defaultZone: http://eureka7001.com:7001/eureka